sudo: false
language: php
php:
  - 5.6
  - 7.0

before_script:
  - npm install -g grunt-cli
  - npm install
  - phpenv config-rm xdebug.ini
  - phpenv rehash

script:
  - npm test
  #- composer self-update
  #- composer install --prefer-dist
  #- composer create-project --repository=https://repo.magento.com magento/marketplace-eqp magento-coding-standard
  #- magento-coding-standard/vendor/bin/phpcs --standard=/apache/magento-coding-standard/MEQP2 --extensions=php --ignore=Test .
