language: php
php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - npm install -g grunt-cli
  - npm install
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer install --dev
  - phpenv rehash
#  - composer create-project --repository=https://repo.magento.com magento/marketplace-eqp magento-coding-standard

script:
  - npm test
  #- vendor/bin/phpcs --standard=/apache/magento-coding-standard/MEQP2 --extensions=php --ignore=Test .
